# k8s/20-web.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: prepup
spec:
  replicas: 2
  selector: { matchLabels: { app: web } }
  template:
    metadata: { labels: { app: web } }
    spec:
      containers:
        - name: web
          image: ghcr.io/arpanchoudhuri/prepup-web:latest
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 80, name: http }]
          env:
            - name: API_BASE_URL
              valueFrom: { configMapKeyRef: { name: web-config, key: API_BASE_URL } }
          readinessProbe: { httpGet: { path: /healthz, port: 80 }, initialDelaySeconds: 5, periodSeconds: 5 }
          livenessProbe:  { httpGet: { path: /healthz, port: 80 }, initialDelaySeconds: 15, periodSeconds: 10 }
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits:   { cpu: "300m", memory: "256Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: prepup
spec:
  selector: { app: web }
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
