apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: prepup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "YourStrong!Passw0rd"
          ports:
            - containerPort: 1433
          resources:
            requests: { cpu: "250m", memory: "512Mi" }
            limits:   { cpu: "1000m", memory: "2Gi" }
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: prepup
spec:
  selector:
    app: mssql
  ports:
    - port: 1433
      targetPort: 1433
  type: ClusterIP