docker-compose.yml
version: "3.8"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1"
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    image: prepup-api
    ports:
      - "8080:8080"
    depends_on:
      mssql:
        condition: service_healthy
    environment:
      - ConnectionStrings__AppDb=Server=mssql,1433;Database=PrepUpDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;MultipleActiveResultSets=true